Traceback (most recent call last):
  File "./simtask.py", line 18, in <module>
    raise Exception( "test exception " )
Exception: test exception 
